### PR TITLE
Lets bring this to MELPA

### PR DESCRIPTION
**Pull request by BenediktBroich**
Features:
- Add melpazoid workflow 
- Fix warnings

Someone created this [melpazoid](https://github.com/riscy/melpazoid) workflow. I did use it to get some packages into MELPA quiet fast. I added it and fixed the errors and warnings. 

Please have a look if everything sill works.

### CODE REVIEW

**Comment by BenediktBroich** [comment]
After that you can create a pull request on MELPA using this ```(ligature :repo "mickeynp/ligature.el" :fetcher github)```

**Comment by mickeynp** [comment]
Looks good -- thank you for the initiative. I did not know about `melpazoid`. However, the reason it's not already on MELPA is due to some serious crash issues on Emacs 27.x. I'm not sure if Emacs's `package.el` respects a version check for itself?

**Comment by BenediktBroich** [comment]
@mickeynp Hmm ok. I see the Issue here. I don't know the answer right now. I will try to find it out. Then contributing the recipe to MELPA should wait, like you said in the Issue.

**Comment by BenediktBroich** [comment]
The pipeline has an issue with the naming of the function `turn-on-ligature-mode`. It should be called `ligature-mode-turn-on`. I did  change this function, but i don't know how many people are using it. So renaming it could brick some stuff.

**Comment by Mihara** [comment]
> So renaming it could brick some stuff.

I believe you could rename it, make an alias on the old name, and mark the alias obsolete? That'll avoid the brickage, and let updating people know. If the pipeline still complains about that, there's got to be something conceptually wrong with the pipeline.

Mind you, with the way how the package currently is not on *elpa at all, updating it will still involve a complicated dance. My current use-package setup grabs it from source with quelpa, and will pick up the change from the repo. Anyone going the more manual route, like I did very recently, will have to go into the config to switch over anyway.

**Comment by BenediktBroich** [comment]
@Mihara yes that is a better idea. I implemented it. Also there is nothing wrong with the pipeline. The pipeline does work. The Problem is caused by [package-lint](https://github.com/purcell/package-lint). It will throw an error caused by the function name. The tool is specifically written for MELPA and does currently not have an option to ignore specific errors. So as long as the function is not removed it will look like it the pipeline has failed.

@mickeynp if the package is permanently broken on emacs 27, then i would check for the emacs version, prevent loading the mode and write a *Messages*. Maybe even an error. Have a look at what i implemented.

**Comment by mickeynp** [comment]
@BenediktBroich --- that is a sensible idea. Let's run with that. 

Thanks, all, for your help.

**Pull request merged**
